steps:
- name: node:lts
  entrypoint: yarn
  args: ["install"]
- name: node:lts
  entrypoint: yarn
  args: ["run", "build"]
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args: ["app", "deploy"]
timeout: "600s"
